### ISSUE TITLE
Quality Assurance: Stream title text overflow

### ISSUE THREAD

**Issue by synicalsyntax** [zulip/zulip-gci#228]
## Create a stream
1. Login as Iago
2. Locate the Navigate cog icon by the Streams section in your left sidebar to navigate to the Streams menu.
3. Click the blue "Create new stream" button.

## Bug 1
![**Bug #1 Screenshot**](https://cloud.githubusercontent.com/assets/15116870/20873712/55feee6a-ba5f-11e6-8d99-ae93c2526afa.png)
**Error with stream titles longer than 100 characters**
1. Create a stream with a long stream title (over 100 characters).
2. The resulting error message will have an overflow of text.

## Bug 2
![bug](https://cloud.githubusercontent.com/assets/15116870/20873788/2c38c406-ba60-11e6-84f1-e3bb9301a80b.png)
**Error with stream titles longer than 48 characters**
1. Create a stream with a long stream title (longer than 48 characters)
2. Click the cog icon located in the upper right corner and click the Administration tab from the dropdown, then click the Streams Deletion tab
3. Find the stream that was just created and click its corresponding Delete stream button.
4. A modal window will appear confirming your stream deletion, but the text will overflow.

## Bug 3
![bugg](https://cloud.githubusercontent.com/assets/15116870/20873873/155921c6-ba61-11e6-85ca-aa57e463df17.png)
**Error with stream titles longer than 30 characters**.
1. Create a stream with a long stream title (longer than 30 characters) using an admin account (ex: Iago)
2. In the left sidebar under the Streams section, hover over the right side of the new stream to make the chevron appear
3. The chevron is obscured by the stream name

**Comment by arpith** [comment]
Created https://github.com/zulip/zulip/issues/2596 - thanks @synicalsyntax!
