### ISSUE TITLE
Quality Assurance

### ISSUE THREAD

**Issue by anirudhjain75** [zulip/zulip-gci#376]
![screenshot_20161215-234841](https://cloud.githubusercontent.com/assets/14249589/21257320/80540abe-c39d-11e6-85e0-3725fe5dbde9.png)

**Comment by anirudhjain75** [comment]
## Steps to verify the bug ##
* Choose any **stream**.
* Scroll down to till you reach the **end**.
* Tap the screen to invoke the write option.
* It does not get invoked.
* For getting it invoked you'll have to go bit up.

**Comment by kunall17** [comment]
> Tap the screen
Where exactly are you tapping on the screen? 

The chatBox (where you write the message) opens up only if you tap the chat message, else not!
