### ISSUE TITLE
Make a task for getting started with the RN mobile app

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-gci#615]
I think the task should just ask the student to get the Zulip RN app working in the simulator, taking notes on any issues they ran into (whether they documentation helped them through those or not).  End result can be a screenshot showing the simulator running.  I'd recommend focusing on Android since that is available on every platform, and we should probably mark this as a more challenging task.

Someone should then test-solve the task, and contribute what they learned back to the main zulip-mobile docs.

**Comment by hackerkid** [comment]
@vishwesh3 @kunall17 @Sam1301 @saketkumar95 Anyone of you interested to write down a task description for this? Something like https://github.com/zulip/zulip-gci/blob/master/tasks/2017/intro-to-zulip-server.md

**Comment by jainkuniya** [comment]
Sure! will do it :) 👍
