### ISSUE TITLE
task idea: Migrate old type hints to python 3 style

### ISSUE THREAD

**Issue by hackerkid** [zulip/zulip-gci#616]
@rht has migrated ~48% of the hints to the Python 3 format using a tool(https://github.com/zulip/zulip/pull/6841) he built. The ones remaining are mostly multi line type hints which the tool is not equipped dealing with.

Proposed task ideas
* Migrate to Python 3 type hints using the tools one file at a time if @rht and @tommyip is able to add multi line type hint support to the tool.
* Manually do the migration if the tool is not complete befored GCI.

https://chat.zulip.org/#narrow/stream/backend/subject/GCI/near/330328

**Comment by rht** [comment]
Note: 48% is the count that has been merged in the codebase so far. While the codebase itself has 86.45% 1-line function [1].

[1] https://github.com/zulip/zulip/pull/7171#issuecomment-341371972
