### ISSUE TITLE
task idea: Add test coverage for linter lines.

### ISSUE THREAD

**Issue by roberthoenig** [zulip/zulip-gci#634]
We have a lot of linter lines left without coverage. Adding coverage is very easy (just add good_lines, bad_lines). I'm thinking of `15 - 20 lines` per task? What's the time consumption we should aim for? I expect 5 rules to take 30-45 minutes, if done well.

**Comment by timabbott** [comment]
I think a few hours for someone who's figured out what's happening is good.

I'd probably do ~10-20/task, maybe varying a bit based on how scary the regular expressions are and easy clusters (e.g. all the markdown rules might be one)...
